export type ASTNode = {
  type: string;
  body?: ASTNode | ASTNode[];
  expressions?: ASTNode[];
  expression?: ASTNode;
  operator?: string;
  name?: string;
  left?: ASTNode;
  right?: ASTNode;
  value?: string | number | null;
  id?: ASTNode;
  init?: ASTNode | null;
  declarations?: ASTNode[];
  test?: ASTNode | null;
  consequent?: ASTNode;
  alternates?: ASTNode[];
  argument?: ASTNode | null;
  arguments?: ASTNode[];
  callee?: ASTNode;
  object?: ASTNode;
  property?: ASTNode;
  elements?: ASTNode[];
  params?: ASTNode[];
  update?: ASTNode | null;
};
